version: "3.5"
services:
  web:
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}_web
    depends_on:
      - db
    env_file:
      - ./config/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ${SERVER_DIR}/media:/var/www/django/media
      - ${SERVER_DIR}/static:/var/www/django/static
    command: [
      "./docker/django/start_remote_web.sh"
    ]
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}_db
    env_file:
      - ./config/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: